package com.zcmedical.common.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "BLOOD_SUGAR".
 */
public class BloodSugar {

    private Long id;
    private int meal_type;
    /** Not-null value. */
    private String user_id;
    private String remarks;
    private int blood_sugar;
    private long measure_time;
    private long created_at;

    public BloodSugar() {
    }

    public BloodSugar(Long id) {
        this.id = id;
    }

    public BloodSugar(Long id, int meal_type, String user_id, String remarks, int blood_sugar, long measure_time, long created_at) {
        this.id = id;
        this.meal_type = meal_type;
        this.user_id = user_id;
        this.remarks = remarks;
        this.blood_sugar = blood_sugar;
        this.measure_time = measure_time;
        this.created_at = created_at;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getMeal_type() {
        return meal_type;
    }

    public void setMeal_type(int meal_type) {
        this.meal_type = meal_type;
    }

    /** Not-null value. */
    public String getUser_id() {
        return user_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public int getBlood_sugar() {
        return blood_sugar;
    }

    public void setBlood_sugar(int blood_sugar) {
        this.blood_sugar = blood_sugar;
    }

    public long getMeasure_time() {
        return measure_time;
    }

    public void setMeasure_time(long measure_time) {
        this.measure_time = measure_time;
    }

    public long getCreated_at() {
        return created_at;
    }

    public void setCreated_at(long created_at) {
        this.created_at = created_at;
    }

    // KEEP METHODS - put your custom methods here
    @Override
    public String toString() {
        return "BloodSugar [id=" + id + ", meal_type=" + meal_type + ", user_id=" + user_id + ", remarks=" + remarks + ", blood_sugar=" + blood_sugar + ", measure_time=" + measure_time
                + ", created_at=" + created_at + "]";
    }
    // KEEP METHODS END

}
