package com.zcmedical.common.db;

import java.util.Map;

import android.database.sqlite.SQLiteDatabase;
import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig weightDaoConfig;
    private final DaoConfig bloodSugarDaoConfig;

    private final WeightDao weightDao;
    private final BloodSugarDao bloodSugarDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        weightDaoConfig = daoConfigMap.get(WeightDao.class).clone();
        weightDaoConfig.initIdentityScope(type);

        bloodSugarDaoConfig = daoConfigMap.get(BloodSugarDao.class).clone();
        bloodSugarDaoConfig.initIdentityScope(type);

        weightDao = new WeightDao(weightDaoConfig, this);
        bloodSugarDao = new BloodSugarDao(bloodSugarDaoConfig, this);

        registerDao(Weight.class, weightDao);
        registerDao(BloodSugar.class, bloodSugarDao);
    }
    
    public void clear() {
        weightDaoConfig.getIdentityScope().clear();
        bloodSugarDaoConfig.getIdentityScope().clear();
    }

    public WeightDao getWeightDao() {
        return weightDao;
    }

    public BloodSugarDao getBloodSugarDao() {
        return bloodSugarDao;
    }

}
