package com.zcmedical.common.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "WEIGHT".
 */
public class Weight {

    private Long id;
    private String user_id;
    private int weight;
    private int height;
    private int target_weight;
    private int bmi;
    private long created_at;

    public Weight() {
    }

    public Weight(Long id) {
        this.id = id;
    }

    public Weight(Long id, String user_id, int weight, int height, int target_weight, int bmi, long created_at) {
        this.id = id;
        this.user_id = user_id;
        this.weight = weight;
        this.height = height;
        this.target_weight = target_weight;
        this.bmi = bmi;
        this.created_at = created_at;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public int getWeight() {
        return weight;
    }

    public void setWeight(int weight) {
        this.weight = weight;
    }

    public int getHeight() {
        return height;
    }

    public void setHeight(int height) {
        this.height = height;
    }

    public int getTarget_weight() {
        return target_weight;
    }

    public void setTarget_weight(int target_weight) {
        this.target_weight = target_weight;
    }

    public int getBmi() {
        return bmi;
    }

    public void setBmi(int bmi) {
        this.bmi = bmi;
    }

    public long getCreated_at() {
        return created_at;
    }

    public void setCreated_at(long created_at) {
        this.created_at = created_at;
    }

    // KEEP METHODS - put your custom methods here
    @Override
    public String toString() {
        return "Weight [id=" + id + ", user_id=" + user_id + ", weight=" + weight + ", height=" + height + ", target_weight=" + target_weight + ", bmi=" + bmi + ", created_at=" + created_at + "]";
    }
    // KEEP METHODS END

}
